# Site settings
title: Moon-shell
keywords: art
description: pictures
email: yevheniiblink@gmail.com
baseurl: ""
url: "https://blinkme182.github.io/MoonShell/"
github_username: "blinkme182"

# Build settings
gems:
  - jekyll-sitemap
show_drafts: false

include:
  - _pages
exclude:
  - docs
markdown: kramdown
permalink: pretty

